# Generated by Django 4.1.5 on 2023-01-22 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('cod_des', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo Destino')),
                ('nombre_des', models.CharField(max_length=55, verbose_name='Nombre Destino')),
                ('precio', models.IntegerField(max_length=6, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombreCompleto', models.CharField(max_length=40, verbose_name='Nombre Completo')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('telefono', models.IntegerField(max_length=9, verbose_name='Telefono')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.destino')),
            ],
        ),
    ]
