# Generated by Django 4.1.5 on 2023-01-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='rut',
            new_name='nro_identif',
        ),
    ]
